### ISSUE TITLE
would it be a good idea to make % (or _) a placeholder in the threading macros?

### ISSUE THREAD

**Issue by AlexKnauth** [greghendershott/rackjure#41]
For example, would something like this be a good idea to provide as an option?

``` racket
#lang rackjure
(~> #"foobar" bytes-length (number->string % 16) string->bytes/utf-8)
;; or maybe this would be better:
(~> #"foobar" bytes-length (number->string _ 16) string->bytes/utf-8)
```

This would make ~> a lot more flexible, meaning the expression could go anywhere, not just in the 2nd position (for ~>) and last position (for ~>>).  Also to me it seems weird to write (number->string 16) when it will really end up as (number->string (bytes-length #"foobar") 16).  
But on the other hand it could interfere with #λ (if % was used) or match (if _ was used).

**Comment by itegebo** [comment]
Alternatively, you could port the [`as->` macro](https://clojuredocs.org/clojure.core/as-%3E).

**Comment by greghendershott** [comment]
Closing this as part of spring-cleaning. These days `rackjure/threading` simply re-provides the [`threading`](http://docs.racket-lang.org/threading/index.html) package, and that does implement using `_` as the placeholder.
