### ISSUE TITLE
definition of `=` in `rackjure/egal` submodule

### ISSUE THREAD

**Issue by mflatt** [greghendershott/rackjure#49]
For some reason, the current version of Racket allows
```
(module+ test
  (require racket)
  (define = ....))
```
but the set-of-scopes macro expander rejects this as defining an identifier that was imported. That causes `rackjure/egal` to not compile, since it has the above pattern (spread over two `module+`s).

**Comment by greghendershott** [comment]
I'll change that.

But out of curiosity:

> For some reason, the current version of Racket allows

Isn't that because bindings from a `module-lang`'s can be shadowed/redefined...

> [(module id module-path form ...)](http://docs.racket-lang.org/reference/module.html#%28form._%28%28quote._~23~25kernel%29._module%29%29)
> ...
> The module-path form must be as for require, and it supplies the initial bindings for the body forms. That is, it is treated like a (require module-path) prefix before the forms, except that the bindings introduced by module-path can be shadowed by definitions and requires in the module body forms.

...and `=` is coming from the module-lang racket/base -- therefore it is supposed to work?

**Comment by greghendershott** [comment]
Oh wait, do you mean `=` also comes from the `(require racket)`?  Therefore I should use `except-in`?

**Comment by mflatt** [comment]
Yes, it's the `=` from `(require racket)` that should create a conflict.
