### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by AlexKnauth** [greghendershott/rackjure#52]
Not really an "issue," but two questions:

How did you get the SCOPE_SNAPSHOT Travis CI build passing for rackjure?
https://travis-ci.org/greghendershott/rackjure/jobs/63492949

And if rackjure is working with SCOPE_SNAPSHOT on Travis CI, then why is rackjure still causing errors like these on my repositories that depend on rackjure?
https://travis-ci.org/AlexKnauth/afl/jobs/67647358#L186

Is it possible that the package server hasn't noticed your changes yet? Or?

**Comment by greghendershott** [comment]
All I did was add it to the build matrix in commit a7dc31c.

That's the same commit showing on http://pkgs.racket-lang.org/#[rackjure] so it's up to date.

That's also the commit in the download from GitHub in your Travis CI build output: https://travis-ci.org/AlexKnauth/afl/jobs/67647358#L147

So... I'm not sure what's going on...?

**Comment by AlexKnauth** [comment]
I just thought to try installing rackjure (and afl, if that worked) from the newest scope-snapshot, but it didn't work, even though it seems to work for you on Travis CI. 
???
Does it work for you, or do you get the same error?

**Comment by AlexKnauth** [comment]
Ok. Rackjure isn't really working with the scope-snapshot, or on HEAD now.
I'm getting this when running `raco test -p rackjure`, because Matthew Flatt fixed a problem with fallbacks. Before, it showed an error when compiling, but actually ran fine, but it turns out it was supposed to show the error when running, and now it does:
```
raco test: (submod "/Users/Alex/Library/Racket/snapshot-6.2.900.4--2015-07-17/pkgs/rackjure/rackjure/test.rkt" test)
lambda: identifier's binding is ambiguous
  context...:
   #(1103 macro) #(1104 module) #(1107 module lambda-reader 0) #(2583 module)
   #(2584 module test 0) #(3725 module) #(3726 module (test test) 0) #(5083 local)
   #(5084 intdef)
  matching binding...:
   #<module-path-index:(rackjure)>
   #(2583 module) #(2584 module test 0)
  matching binding...:
   #<module-path-index:(racket/base)>
   #(1104 module) #(1107 module lambda-reader 0)
  in: lambda
  context...:
   standard-module-name-resolver
   (submod /Applications/Racket/2015-07-17/Racket v6.2.900.4/share/pkgs/compiler-lib/compiler/commands/test.rkt process): [running body]
test.rkt: raco test: non-zero exit: 1
```
I'll make a pull request with one way to fix this that worked for `afl`.
